name: NodeJS Build and Deploy

on:
  push:
    branches:
      - main  # Ajusta el nombre de tu rama principal si es necesario
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - uses: actions/checkout@v3

      # Set up Node.js version
      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install dependencies and tools
      - name: Install dependencies
        run: |
          yarn install --ignore-scripts
          sudo apt-get update -y && sudo apt-get install -y zip

      # Lint and check for i18n updates
      - name: Lint and check locale files
        run: |
          yarn lint
          yarn i18n && git diff --quiet || (echo "Locale files are out of date. Please run 'yarn i18n'" && exit 1)

      # Build the project
      - name: Build project
        run: |
          NODE_ENV=production yarn build
          cp dist/index.html dist/404.html
          cd dist && zip -r ../nvus.zip . && cd ..

      # Upload the artifact (zip file) for later stages
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: nvus.zip
          path: nvus.zip

  deploy-review:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: review/${{ github.ref_name }}
      url: https://${{ github.ref_name }}.gitlab.com  # Adjust according to your needs
    steps:
      # Download the artifact from the previous build job
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: nvus.zip

      # Install unzip tool and deploy
      - name: Deploy to Surge
        run: |
          sudo apt-get update -y && sudo apt-get install -y unzip
          unzip nvus.zip -d dist
          npx -y surge dist ${{ github.ref_name }}.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

  deploy-pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download the artifact from the build job
      - name: Download artifact for pages deployment
        uses: actions/download-artifact@v3
        with:
          name: nvus.zip

      # Unzip and deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          sudo apt-get update -y && sudo apt-get install -y unzip
          unzip nvus.zip -d public

      # Push to GitHub Pages
      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          folder: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
